class Employee {
    employeeId = null;
    employeeCode = null;
    firstName = null;
    lastName = null;
    fullName = "";
    address = "";
    email = "";
    identifyNumber = "";
    dateOfBirth = "";
    identifyDate = "";
    identifyPlace = "";
    joinDate = null;
    martialStatus = null;
    educationalBackground = null;
    departmentId = "";
    departmentName = "";
    workStatus = null;
    personalTaxCode = null;
    salary = null;
    gender = null;
    genderName = "";
    phoneNumber = "";
    telephoneNumber = "";
    bankAccountNumber = "";
    bankName = "";
    bankBranchName = "";
    positionName = "";
    createdDate = null;
    createdBy = null;
    modifiedDate = null;
    modifiedBy = null;
}

export default Employee;